### ISSUE TITLE
Bug: BMI Bar `<canvas>` Exceeds Card Border

### ISSUE THREAD

**Issue by bag026** [ipuppet/sport-tracker#49]
**Describe the bug**
The colored BMI bar <canvas> exceeds the border of its card. This happens because the <canvas> is set to a fixed width (e.g., width="400"), but the card/container is responsive or smaller, causing the canvas to overflow its parent.
Here’s a clear GitHub issue report you can use:

---

**How to Reproduce**
1. View the BMI card on a smaller screen or resize the browser window.
2. The BMI bar overflows the card border.

---
**Current status**
![Image](https://github.com/user-attachments/assets/6761b10c-af35-490f-9757-79350277769e)

---
**Expected behavior**  

The BMI bar should always fit inside its card/container, regardless of screen size.

---
**How to Fix**

- **Remove the fixed `width` attribute** from the `<canvas>` tag in your HTML.
- **Add CSS** to make the canvas responsive and fill its parent container.

**Example CSS:**
```css
.bmi-bar-container {
    width: 100%;
    overflow: hidden;
}
.bmi-bar-container canvas {
    width: 100% !important;
    height: 48px !important;
    max-width: 100%;
    display: block;
}
```

**Example HTML:**
```html
<div class="bmi-bar-container my-3" style="position:relative; height:48px;">
    <canvas id="bmiBar" height="48"></canvas>
</div>
```
*(No `width="400"` on the `<canvas>`)*

**Tags:** `bug` `frontend` `css`
